"""LLMProtocolAdapter protocol."""
from __future__ import annotations

from typing import AsyncIterator, Literal, Protocol

from ai_recon.core.models import ChatResponse, Delta, Message


class LLMProtocolAdapter(Protocol):
    async def chat(self, messages: list[Message], **opts) -> ChatResponse: ...
    async def stream_chat(self, messages: list[Message], **opts) -> AsyncIterator[Delta]: ...
    async def embed(self, texts: list[str]) -> list[list[float]]: ...
    def supports(self, capability: Literal["streaming", "tools", "vision", "logprobs"]) -> bool: ...
    def model_id(self) -> str | None: ...
